services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PunktDe\PtSentryClient\:
    resource: '../Classes/*'

  PunktDe\PtSentryClient\Handler\Frontend\SentryProductionExceptionHandler:
    public: true
